### ISSUE TITLE
Does not work with Gruntfile.coffee

### ISSUE THREAD

**Issue by jdiaz5513** [voceconnect/grunt-peon-gui#3]
Will only run if the Gruntfile is written in pure js.

That is thanks to this hardcoded command: 
grunt --gruntfile Gruntfile.js --base . TASK

Is specifying the Gruntfile via --gruntfile really necessary here?

**Comment by markparolisi** [comment]
@jdiaz5513 
It was necessary for the custom configuration we were doing when the plugin was first built. I will look to do a refactor soon to correct this. Thanks

**Comment by markparolisi** [comment]
@jdiaz5513 
Now that I look at my history, it seems like you must be running and old version of the plugin. That "bug" was fixed months ago. I am doing some cleanup anyway and will publish a new version to NPM so just set your package version to "latest" and pull again soon.

Thanks.
