### ISSUE TITLE
Fatal error: spawn ENOENT when running any tasks

### ISSUE THREAD

**Issue by esteinborn** [voceconnect/grunt-peon-gui#4]
(On Windows 7)
When I try to run a task from the GUI, my command line spits out:

```
Running: grunt --gruntfile Gruntfile.js --base . sass
Fatal error: spawn ENOENT
```

In addition, when I run `grunt gui` it tells me:

```
Warning: Native modules not compiled.  XOR performance will be degraded.
Warning: Native modules not compiled.  UTF-8 validation disabled.
```

So I'm not sure if that has anything to do with this error I'm getting or not.

**Comment by markparolisi** [comment]
@esteinborn 
It may be a Windows thing. I'll have to spin up a VM and test there. 
Thanks.

**Comment by markparolisi** [comment]
@esteinborn 
Actually,
duplicates #2

**Comment by esteinborn** [comment]
Yeah, i didn't click that because it didnt have my error in the subject line. My bad.

I'm install python and v c++dependencies now and I'm going to re-test to see if it fixes it. a GUI is going to be very beneficial to my organization very soon.
